EXECUTABLE := paracuda
CUFILES := test.cu nvidia_kernel.cu
CU_DEPS := kernel.cu paracuda.h paracuda_struct.h paracuda_map.h paracuda_scan.h paracuda_segmentedScan.h nvidia_scan.h nvidia_large_kernel.cu
CCFILES := main.cpp


include ../../common/common.mk

